/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gsp;

import controleur.CodeAuto;
import controleur.Coeur_Gsp;
import controleur.ConnectDataBase;
import static java.lang.Thread.sleep;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jordie
 */
public class Menu_principal extends javax.swing.JFrame {

    Coeur_Gsp cg = new Coeur_Gsp();
    private Statement st;
    private ResultSet rs;
    public String pseudo, madate;
    int count = 0;
    private String vide;
    private DefaultTableModel dtm;
    String entete[] = {"Date", "Produit", "Quantité entrée", "Prix unitaire", "Prix total", "Quantité sortie", "Prix unitaire", "Prix total", "Quantité destockée", "Quantité en stock"};
    Object row[] = new Object[10];
    private String codcli;
    private double qte;
    private double rem;
    private String nomcli;
    String numfact;
    CodeAuto ca = new CodeAuto();
    private double total;
    private double pht;
    private double montPaie;
    private double tva;

    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() {
        initComponents();
        setLocationRelativeTo(null);
        //imagePanel1.setImage(new ImageIcon(this.getClass().getResource("/image/b1.png")).getImage());
        dateheure();
        //tabFiche.setDefaultRenderer(Object.class, new SubJTable());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labExp = new javax.swing.JLabel();
        labExp8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        labExp9 = new javax.swing.JLabel();
        labExp10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        labExp11 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        labExp12 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        labExp13 = new javax.swing.JLabel();
        labExp14 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        labSeuil = new javax.swing.JLabel();
        labDes = new javax.swing.JLabel();
        labExp18 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        labExp17 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        labHeure = new javax.swing.JLabel();
        labDate = new javax.swing.JLabel();
        labUser = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(null);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Combo Chart_25px.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 40, 40);

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Statistiques générales");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 0, 220, 40);

        jLabel8.setBackground(new java.awt.Color(104, 151, 215));
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 0, 330, 40);

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel15.setText("   Produits expirés :");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 270, 210, 20);

        labExp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labExp.setText("0");
        labExp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(labExp);
        labExp.setBounds(230, 270, 80, 20);

        labExp8.setBackground(new java.awt.Color(104, 151, 215));
        labExp8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labExp8.setText("0");
        labExp8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(labExp8);
        labExp8.setBounds(230, 50, 80, 20);

        jLabel23.setBackground(new java.awt.Color(104, 151, 215));
        jLabel23.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("   Produits expirés :");
        jLabel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel23.setOpaque(true);
        jPanel2.add(jLabel23);
        jLabel23.setBounds(20, 50, 210, 20);

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel24.setText("   Produits expirés :");
        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel24);
        jLabel24.setBounds(20, 70, 210, 20);

        labExp9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labExp9.setText("0");
        labExp9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(labExp9);
        labExp9.setBounds(230, 70, 80, 20);

        labExp10.setBackground(new java.awt.Color(104, 151, 215));
        labExp10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labExp10.setText("0");
        labExp10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(labExp10);
        labExp10.setBounds(230, 90, 80, 20);

        jLabel25.setBackground(new java.awt.Color(104, 151, 215));
        jLabel25.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("   Produits expirés :");
        jLabel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel25.setOpaque(true);
        jPanel2.add(jLabel25);
        jLabel25.setBounds(20, 90, 210, 20);

        labExp11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labExp11.setText("0");
        labExp11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(labExp11);
        labExp11.setBounds(230, 110, 80, 20);

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel26.setText("   Produits expirés :");
        jLabel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel26);
        jLabel26.setBounds(20, 110, 210, 20);

        labExp12.setBackground(new java.awt.Color(104, 151, 215));
        labExp12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labExp12.setText("0");
        labExp12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(labExp12);
        labExp12.setBounds(230, 130, 80, 20);

        jLabel27.setBackground(new java.awt.Color(104, 151, 215));
        jLabel27.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("   Produits expirés :");
        jLabel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel27.setOpaque(true);
        jPanel2.add(jLabel27);
        jLabel27.setBounds(20, 130, 210, 20);

        labExp13.setBackground(new java.awt.Color(104, 151, 215));
        labExp13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labExp13.setText("0");
        labExp13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(labExp13);
        labExp13.setBounds(230, 170, 80, 20);

        labExp14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labExp14.setText("0");
        labExp14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(labExp14);
        labExp14.setBounds(230, 150, 80, 20);

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel28.setText("   Produits expirés :");
        jLabel28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel28);
        jLabel28.setBounds(20, 150, 210, 20);

        jLabel29.setBackground(new java.awt.Color(104, 151, 215));
        jLabel29.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("   Produits expirés :");
        jLabel29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel29.setOpaque(true);
        jPanel2.add(jLabel29);
        jLabel29.setBounds(20, 170, 210, 20);

        labSeuil.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labSeuil.setText("0");
        labSeuil.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(labSeuil);
        labSeuil.setBounds(230, 230, 80, 20);

        labDes.setBackground(new java.awt.Color(104, 151, 215));
        labDes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labDes.setText("0");
        labDes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(labDes);
        labDes.setBounds(230, 250, 80, 20);

        labExp18.setBackground(new java.awt.Color(104, 151, 215));
        labExp18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labExp18.setText("0");
        labExp18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(labExp18);
        labExp18.setBounds(230, 210, 80, 20);

        jLabel30.setBackground(new java.awt.Color(104, 151, 215));
        jLabel30.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("   Produits déstockés :");
        jLabel30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel30.setOpaque(true);
        jPanel2.add(jLabel30);
        jLabel30.setBounds(20, 250, 210, 20);

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel31.setText("   Produits en seuil d'alerte :");
        jLabel31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel31);
        jLabel31.setBounds(20, 230, 210, 20);

        labExp17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labExp17.setText("0");
        labExp17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(labExp17);
        labExp17.setBounds(230, 190, 80, 20);

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel32.setText("   Produits expirés :");
        jLabel32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel32);
        jLabel32.setBounds(20, 190, 210, 20);

        jLabel33.setBackground(new java.awt.Color(104, 151, 215));
        jLabel33.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("   Produits expirés :");
        jLabel33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel33.setOpaque(true);
        jPanel2.add(jLabel33);
        jLabel33.setBounds(20, 210, 210, 20);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        labHeure.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labHeure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labHeure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clock.png"))); // NOI18N
        labHeure.setText("00 : 00 :00");

        labDate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/date.png"))); // NOI18N
        labDate.setText("Aujourd'hui, c'est le :");

        labUser.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        labUser.setText("Utilisateur courant :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(labUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labDate)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labHeure, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(labHeure, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
            .addComponent(labDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jToolBar1.setFloatable(false);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator6);
        jToolBar1.add(jSeparator5);

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/new.gif"))); // NOI18N
        jButton1.setText("          ");
        jButton1.setToolTipText("Nouveau produit");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolBar1.add(jButton1);

        jButton4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_usradd.png"))); // NOI18N
        jButton4.setText("          ");
        jButton4.setToolTipText("Nouveau client");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolBar1.add(jButton4);

        jButton5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/b_usrlist.png"))); // NOI18N
        jButton5.setText("          ");
        jButton5.setToolTipText("Nouveau utilisateur");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolBar1.add(jButton5);

        jButton6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bd_browse.png"))); // NOI18N
        jButton6.setText("          ");
        jButton6.setToolTipText("Nouvelle vente");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolBar1.add(jButton6);

        jButton7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reload.png"))); // NOI18N
        jButton7.setText("          ");
        jButton7.setToolTipText("Nouvelle vente");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        jPanel4.setBackground(new java.awt.Color(104, 151, 215));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GSP");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gsp.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Fichier");
        jMenu1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenu5.setText("Clients");
        jMenu5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem1.setText("Enregistrement");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem2.setText("Mise à jour");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenu1.add(jMenu5);

        jMenu6.setText("Catégories");
        jMenu6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem3.setText("Enregistrement");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem4.setText("Mise à jour");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenu1.add(jMenu6);

        jMenu7.setText("Devises");
        jMenu7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem5.setText("Enregistrement");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem6.setText("Mise à jour");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenu1.add(jMenu7);

        jMenu8.setText("Produits");
        jMenu8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem7.setText("Enregistrement");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem8.setText("Mise à jour");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);

        jMenu1.add(jMenu8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exploitation");
        jMenu2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenu12.setText("Entrée en stock");
        jMenu12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem9.setText("Enregistrement");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem9);

        jMenuItem12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem12.setText("Mise à jour");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem12);

        jMenu2.add(jMenu12);

        jMenuItem13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem13.setText("Génération des codes barres");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem14.setText("Déstockage");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem16.setText("Vente");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Rapport d'exploitation");
        jMenu3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem15.setText("Produits déstockés");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem15);

        jMenuItem17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem17.setText("Factures établies");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem17);

        jMenuItem18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem18.setText("Stock Courant");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem18);

        jMenuItem23.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem23.setText("Liste d'entrées");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem23);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Paramètre");
        jMenu4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenu9.setText("Utilisateur");
        jMenu9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem10.setText("Enregistrement");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem11.setText("Mise à jour");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem11);

        jMenu4.add(jMenu9);

        jMenuItem19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jMenuItem19.setText("Mon GSP");
        jMenu4.add(jMenuItem19);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Client cli = new Client(new javax.swing.JFrame(), true);
        cli.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        UpDateClient cli = new UpDateClient(new javax.swing.JFrame(), true);
        cli.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Categorie cat = new Categorie(new javax.swing.JFrame(), true);
        cat.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        UpDateCategorie cat = new UpDateCategorie(new javax.swing.JFrame(), true);
        cat.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Devise dev = new Devise(new javax.swing.JFrame(), true);
        dev.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        UpDateDevise dev = new UpDateDevise(new javax.swing.JFrame(), true);
        dev.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Produit prod = new Produit(new javax.swing.JFrame(), true);
        prod.madate = madate;
        prod.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        UpDateProduit prod = new UpDateProduit(new javax.swing.JFrame(), true);
        prod.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Utilisateur util = new Utilisateur(new javax.swing.JFrame(), true);
        util.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        UpDateUtilisateur util = new UpDateUtilisateur(new javax.swing.JFrame(), true);
        util.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Stock stock = new Stock(new javax.swing.JFrame(), true);
        stock.pseudo = pseudo;
        stock.madate = madate;
        stock.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        UpDateStock stock = new UpDateStock(new javax.swing.JFrame(), true);
        stock.pseudo = pseudo;
        stock.madate = madate;
        stock.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        CodeBarre stock = new CodeBarre(new javax.swing.JFrame(), true);
        stock.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        Destocker destock = new Destocker(new javax.swing.JFrame(), true);
        destock.madate = madate;
        destock.pseudo = pseudo;
        destock.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        ListeDestocker destock = new ListeDestocker(new javax.swing.JFrame(), true);
        destock.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
//        ficheDestock();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        ficheDestock();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        Vente ven = new Vente(new javax.swing.JFrame(), true);
        ven.txtDate.setText(madate);
        ven.txtCaisse.setText(pseudo);
        ven.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        ListeFac fac = new ListeFac(new javax.swing.JFrame(), true);
        fac.madate = madate;
        fac.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        ListeStock stock = new ListeStock(new javax.swing.JFrame(), true);
        stock.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        ListeEntre entre = new ListeEntre(new javax.swing.JFrame(), true);
        entre.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    public void dateheure() {
        Thread clock = new Thread() {
            private int annee;
            private int jour;
            private String month;

            @Override
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();
                    int mois = cal.get(Calendar.MONTH);
                    annee = cal.get(Calendar.YEAR);
                    jour = cal.get(Calendar.DAY_OF_MONTH);
                    int seconde = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int heure = cal.get(Calendar.HOUR_OF_DAY);
                    int jourse = cal.get(Calendar.DAY_OF_WEEK);
                    month = "";
                    String day = "";
                    switch (jourse - 1) {
                        case 1:
                            day = "Lundi";
                            break;
                        case 2:
                            day = "Mardi";
                            break;
                        case 3:
                            day = "Mercredi";
                            break;
                        case 4:
                            day = "Jeudi";
                            break;
                        case 5:
                            day = "Vendredi";
                            break;
                        case 6:
                            day = "Samedi";
                            break;
                        default:
                            day = "Dimanche";
                            break;
                    }

                    switch (mois + 1) {
                        case 1:
                            month = "Janvier";
                            break;
                        case 2:
                            month = "Février";
                            break;
                        case 3:
                            month = "Mars";
                            break;
                        case 4:
                            month = "Avril";
                            break;
                        case 5:
                            month = "Mai";
                            break;
                        case 6:
                            month = "Juin";
                            break;
                        case 7:
                            month = "Juillet";
                            break;
                        case 8:
                            month = "Août";
                            break;
                        case 9:
                            month = "Septembre";
                            break;
                        case 10:
                            month = "Octobre";
                            break;
                        case 11:
                            month = "Novembre";
                            break;
                        case 12:
                            month = "Décembre";
                            break;
                    }
                    int mmois = mois + 1;
                    String m = "", j = "";
                    int mm = mois + 1;
                    String mmmois;
                    if (mm < 10) {
                        mmmois = "0" + mm;
                    } else {
                        mmmois = String.valueOf(mm);
                    }
                    if (jour < 10) {
                        j = "0" + jour;
                    } else {
                        j = String.valueOf(jour);
                    }
                    String h = "", mi = "", s = "";
                    if (heure < 10) {
                        h = "0" + heure;
                    } else {
                        h = String.valueOf(heure);
                    }
                    if (minute < 10) {
                        mi = "0" + minute;
                    } else {
                        mi = String.valueOf(minute);
                    }
                    if (seconde < 10) {
                        s = "0" + seconde;
                    } else {
                        s = String.valueOf(seconde);
                    }
                    labExp.setText(String.valueOf(expire()));
                    labDes.setText(String.valueOf(destocker()));
                    labSeuil.setText(String.valueOf(seuilDalerte()));
                    labDate.setText("" + day + " le" + " " + j + " " + month + " " + annee);
                    labHeure.setText("" + h + ":" + mi + ":" + s);
                    madate = annee + "-" + mmmois + "-" + j;
                    //cg.initialisationFiche(madate);
                    try {
                        sleep(1000);
                    } catch (InterruptedException e) {
                        cg.boiteDeDialogue(e.toString(), "erreur");
                    }
                }
            }
        };
        clock.start();
    }

//    public void ficheDestock() {
//        try {
//            st = new ConnectDataBase().getConnexion().createStatement();
//            dtm = new DefaultTableModel(null, entete);
//            rs = st.executeQuery("select fichedestock.dateenr as date,produit.libprod as produits,fichedestock.qteent as quantit_entrée,fichedestock.puent as prix_unitaire,fichedestock.qteent*fichedestock.puent as prix_total,fichedestock.qtesor as quantité_sortie,fichedestock.pusor as prix_unitaire,fichedestock.qtesor*fichedestock.pusor as prix_total,fichedestock.qtedes as quantité_destockée, fichedestock.qtesto as quantité_stockée from fichedestock inner join produit on produit.codprod=fichedestock.codprod");
//            while (rs.next()) {
//                row[0] = rs.getObject(1);
//                row[1] = rs.getObject(2);
//                row[2] = rs.getObject(3);
//                row[3] = rs.getObject(4);
//                row[4] = rs.getObject(5);
//                row[5] = rs.getObject(6);
//                row[6] = rs.getObject(7);
//                row[7] = rs.getObject(8);
//                row[8] = rs.getObject(9);
//                row[9] = rs.getObject(10);
//                dtm.addRow(row);
//            }
//            tabFiche.setModel(dtm);
//            tabFiche.getColumnModel().getColumn(0).setPreferredWidth(100);
//            tabFiche.getColumnModel().getColumn(1).setPreferredWidth(300);
//            tabFiche.getColumnModel().getColumn(2).setPreferredWidth(100);
//            tabFiche.getColumnModel().getColumn(3).setPreferredWidth(100);
//            tabFiche.getColumnModel().getColumn(4).setPreferredWidth(100);
//            tabFiche.getColumnModel().getColumn(5).setPreferredWidth(100);
//            tabFiche.getColumnModel().getColumn(6).setPreferredWidth(100);
//            tabFiche.getColumnModel().getColumn(7).setPreferredWidth(100);
//            tabFiche.getColumnModel().getColumn(8).setPreferredWidth(110);
//            tabFiche.getColumnModel().getColumn(9).setPreferredWidth(110);
//            rs.close();
//            st.close();
//        } catch (SQLException e) {
//            cg.boiteDeDialogue(e.toString(), "erreur");
//        }
//    }
    public int expire() {
        try {
            vide = "1111-11-11";
            st = new ConnectDataBase().getConnexion().createStatement();
            rs = st.executeQuery("select count(*) from destocker");
            while (rs.next()) {
                count = rs.getInt(1);
            }
            if (count == 0) {
                rs = st.executeQuery("select count(*) from stocker where stocker.dateexp <= '" + madate + "' and stocker.dateexp != '" + vide + "'");
                while (rs.next()) {
                    count = rs.getInt(1);
                }
            } else {
                rs = st.executeQuery("select count(*) from stocker inner join destocker on destocker.codebar != stocker.codebar where stocker.dateexp <= '" + madate + "' and stocker.dateexp != '" + vide + "'");
                while (rs.next()) {
                    count = rs.getInt(1);
                }
            }
            st.close();
            rs.close();
            return count;
        } catch (SQLException e) {
            cg.boiteDeDialogue(e.toString(), "erreur");
            return count;
        }
    }

    public int destocker() {
        try {
            vide = "";
            st = new ConnectDataBase().getConnexion().createStatement();
            rs = st.executeQuery("select count(*) from destocker");
            while (rs.next()) {
                count = rs.getInt(1);
            }
            st.close();
            rs.close();
            return count;
        } catch (SQLException e) {
            cg.boiteDeDialogue(e.toString(), "erreur");
            return count;
        }
    }

    public int seuilDalerte() {
        try {
            vide = "";
            st = new ConnectDataBase().getConnexion().createStatement();
            rs = st.executeQuery("select count(*) from stockCourant inner join produit on produit.codprod=stockCourant.codprod where stockCourant.qte<=produit.qtemin");
            while (rs.next()) {
                count = rs.getInt(1);
            }
            st.close();
            rs.close();
            return count;
        } catch (SQLException e) {
            cg.boiteDeDialogue(e.toString(), "erreur");
            return count;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labDes;
    private javax.swing.JLabel labExp;
    private javax.swing.JLabel labExp10;
    private javax.swing.JLabel labExp11;
    private javax.swing.JLabel labExp12;
    private javax.swing.JLabel labExp13;
    private javax.swing.JLabel labExp14;
    private javax.swing.JLabel labExp17;
    private javax.swing.JLabel labExp18;
    private javax.swing.JLabel labExp8;
    private javax.swing.JLabel labExp9;
    private javax.swing.JLabel labHeure;
    private javax.swing.JLabel labSeuil;
    public javax.swing.JLabel labUser;
    // End of variables declaration//GEN-END:variables
}
