/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gsp;

import controleur.Coeur_Gsp;
import controleur.ConnectDataBase;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTextField;

/**
 *
 * @author Jordie
 */
public class Stock extends javax.swing.JDialog {

    Coeur_Gsp cg = new Coeur_Gsp();
    public String operation = "";
    public int ligne;
    public String pseudo, madate, codebar;
    private Statement st;
    private ResultSet rs;
    public String dateenr;
    private double qteent;
    private double puent;
    private double qtesor;
    private double pusor;
    private double qtedes;
    public double qtesto;
    private int count;
    private int codnum;
    private double qtestock;
    private double qtesto1;

    /**
     * Creates new form Stock
     */
    public Stock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmbProd = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQte = new javax.swing.JTextField();
        chExp = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDateExp = new com.toedter.calendar.JDateChooser();
        txtDateFab = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mise à jour entrée");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 0, 230, 40);

        jLabel4.setBackground(new java.awt.Color(104, 151, 215));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 460, 40);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Code barre");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 60, 90, 15);

        txtCode.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel1.add(txtCode);
        txtCode.setBounds(80, 80, 290, 30);

        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        jButton1.setText("Annuler");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(260, 360, 110, 50);

        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.gif"))); // NOI18N
        jButton2.setText("Enregistrer");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(80, 360, 110, 50);

        cmbProd.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel1.add(cmbProd);
        cmbProd.setBounds(80, 140, 290, 30);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Produit");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 120, 90, 15);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Quantité");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 180, 90, 15);

        txtQte.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtQte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(txtQte);
        txtQte.setBounds(80, 200, 290, 30);

        chExp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        chExp.setText("Expirant");
        chExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chExpActionPerformed(evt);
            }
        });
        jPanel1.add(chExp);
        chExp.setBounds(80, 240, 100, 23);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, null, null, null, new java.awt.Font("Verdana", 0, 12))); // NOI18N
        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setText("Date d'expiration");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(150, 10, 140, 15);

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setText("Date de fabrication");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 10, 140, 15);

        txtDateExp.setDateFormatString("yyyy-MM-dd");
        txtDateExp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel2.add(txtDateExp);
        txtDateExp.setBounds(150, 30, 120, 30);

        txtDateFab.setDateFormatString("yyyy-MM-dd");
        txtDateFab.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel2.add(txtDateFab);
        txtDateFab.setBounds(20, 30, 120, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(80, 270, 290, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cg.remplirCombo("libprod", "produit", cmbProd);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtCode.setText("");
        cmbProd.setSelectedIndex(0);
        txtQte.setText("");
        chExp.setSelected(false);
        txtDateFab.setDate(null);
        txtDateExp.setDate(null);
        txtCode.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            st = new ConnectDataBase().getConnexion().createStatement();
            if (txtCode.getText().isEmpty() || txtQte.getText().isEmpty()) {
                cg.boiteDeDialogue("Veuillez remplir toute les zones.", "erreur");
            } else {
                if (operation.equals("modifier")) {
                    rs = st.executeQuery("select qte from stockCourant where codprod='" + cg.retournerIdentifiant("codprod", "libprod", "produit", cmbProd) + "'");
                    while (rs.next()) {
                        qtesto1 = rs.getDouble(1);
                    }
                    qtesto = qtesto1 - qtesto + (Double.parseDouble(txtQte.getText()));
                    if (chExp.isSelected()) {
                        if (((JTextField) txtDateFab.getDateEditor().getUiComponent()).getText().isEmpty() || ((JTextField) txtDateExp.getDateEditor().getUiComponent()).getText().isEmpty()) {
                            cg.boiteDeDialogue("Veuillez remplir la date de fabrication et expiration.", "erreur");
                        } else {
                            cg.miseAjour("update stocker set codprod='" + cg.retournerIdentifiant("codprod", "libprod", "produit", cmbProd) + "',coduti='" + cg.ligne("coduti", "utilisateur", pseudo, "pseudo") + "',codebar='" + cg.optimiser(txtCode) + "',qte='" + cg.optimiser(txtQte) + "',datefab='" + cg.optimiser(((JTextField) txtDateFab.getDateEditor().getUiComponent())) + "',dateexp='" + cg.optimiser(((JTextField) txtDateExp.getDateEditor().getUiComponent())) + "',datestock='" + madate + "' where numsto='" + ligne + "'");
                            cg.miseAjour("update stockCourant set qte='" + qtesto + "' where codprod='" + cg.retournerIdentifiant("codprod", "libprod", "produit", cmbProd) + "'");
                        }
                    } else {
                        cg.miseAjour("update stocker set codprod='" + cg.retournerIdentifiant("codprod", "libprod", "produit", cmbProd) + "',coduti='" + cg.ligne("coduti", "utilisateur", pseudo, "pseudo") + "',codebar='" + cg.optimiser(txtCode) + "',qte='" + cg.optimiser(txtQte) + "',datestock='" + madate + "' where numsto='" + ligne + "'");
                        cg.miseAjour("update stockCourant set qte='" + qtesto + "' where codprod='" + cg.retournerIdentifiant("codprod", "libprod", "produit", cmbProd) + "'");
                    }
                    //fiche_de_stock(ligne);
                    cg.boiteDeDialogue("Stock modifié avec succès.", "information");
                    txtCode.setText("");
                    cmbProd.setSelectedIndex(0);
                    txtQte.setText("");
                    txtQte.setText("");
                    chExp.setSelected(false);
                    txtDateFab.setDate(null);
                    txtDateExp.setDate(null);
                    txtCode.requestFocus();
                } else {
                    String vide = "1111-11-11";
                    if (chExp.isSelected()) {
                        if (((JTextField) txtDateFab.getDateEditor().getUiComponent()).getText().isEmpty() || ((JTextField) txtDateExp.getDateEditor().getUiComponent()).getText().isEmpty()) {
                            cg.boiteDeDialogue("Veuillez remplir la date de fabrication et expiration.", "erreur");
                        } else {
                            cg.miseAjour("insert into stocker values('" + cg.nouvelleLigne("numsto", "stocker") + "','" + cg.retournerIdentifiant("codprod", "libprod", "produit", cmbProd) + "','" + cg.ligne("coduti", "utilisateur", pseudo, "pseudo") + "','" + cg.optimiser(txtCode) + "','" + cg.optimiser(txtQte) + "','" + cg.optimiser(((JTextField) txtDateFab.getDateEditor().getUiComponent())) + "','" + cg.optimiser(((JTextField) txtDateExp.getDateEditor().getUiComponent())) + "','" + madate + "')");
                        }
                    } else {
                        cg.miseAjour("insert into stocker values('" + cg.nouvelleLigne("numsto", "stocker") + "','" + cg.retournerIdentifiant("codprod", "libprod", "produit", cmbProd) + "','" + cg.ligne("coduti", "utilisateur", pseudo, "pseudo") + "','" + cg.optimiser(txtCode) + "','" + cg.optimiser(txtQte) + "','" + vide + "','" + vide + "','" + madate + "')");
                    }
                    rs = st.executeQuery("select qte from stockCourant where codprod='" + cg.retournerIdentifiant("codprod", "libprod", "produit", cmbProd) + "'");
                    while (rs.next()) {
                        qtestock = rs.getDouble(1);
                    }
                    if (qtestock == 0.0) {
                        cg.miseAjour("insert into stockCourant values('" + cg.retournerIdentifiant("codprod", "libprod", "produit", cmbProd) + "','" + txtQte.getText() + "')");
                    } else {
                        cg.miseAjour("update stockCourant set qte='" + (qtestock + Double.parseDouble(txtQte.getText())) + "' where codprod='" + cg.retournerIdentifiant("codprod", "libprod", "produit", cmbProd) + "'");
                    }
                    rs.close();
                    st.close();
                    //fiche_de_stock(ligne);
                    //fiche_de_stock(txtCode.getText());
                    cg.boiteDeDialogue("Produit stocké avec succès.", "information");
                    txtCode.setText("");
                    cmbProd.setSelectedIndex(0);
                    txtQte.setText("");
                    chExp.setSelected(false);
                    txtDateFab.setDate(null);
                    txtDateExp.setDate(null);
                    txtCode.requestFocus();
                }
            }
        } catch (Exception e) {
            cg.boiteDeDialogue(e.toString(), "erreur");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void chExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chExpActionPerformed

    public void fiche_de_stock(int mycod) {
        try {
            if (operation.equals("modifier")) {
                cg.miseAjour("update fichedestock set qteent='" + cg.optimiser(txtQte) + "',puent='" + cg.getPaUnitaire(cmbProd.getSelectedItem().toString()) + "',qtesor='" + 0 + "',pusor='" + cg.getPvUnitaire(cmbProd.getSelectedItem().toString()) + "',qtedes='" + 0 + "',qtesto='" + 0 + "' where codprod='" + cg.retournerIdentifiant("codprod", "libprod", "produit", cmbProd) + "' and dateenr='" + madate + "'");
            } else {
                cg.miseAjour("insert into fichedestock values('" + cg.nouvelleLigne("codnum", "fichedestock") + "','" + cg.retournerIdentifiant("codprod", "libprod", "produit", cmbProd) + "','" + madate + "','" + cg.optimiser(txtQte) + "','" + cg.getPaUnitaire(cmbProd.getSelectedItem().toString()) + "','" + 0 + "','" + cg.getPvUnitaire(cmbProd.getSelectedItem().toString()) + "','" + 0 + "','" + 0 + "')");
            }
        } catch (Exception e) {
            cg.boiteDeDialogue(e.toString(), "erreur");
        }
    }

    public void fiche_de_stock(String codebarre) {
        try {
            st = new ConnectDataBase().getConnexion().createStatement();
            rs = st.executeQuery("select count(*) from fichedestock where codprod='" + cg.getCodrod(txtCode.getText()) + "'");
            while (rs.next()) {
                count = rs.getInt(1);
            }
            if (count == 0) {
                st.executeUpdate("insert into fichedestock values('" + cg.nouvelleLigne("codnum", "fichedestock") + "','" + cg.getCodrod(txtCode.getText()) + "','" + madate + "','" + txtQte.getText() + "','" + cg.getPaUnitaire(cmbProd.getSelectedItem().toString()) + "','" + 0 + "','" + cg.getPvUnitaire(cmbProd.getSelectedItem().toString()) + "','" + 0 + "','" + txtQte.getText() + "')");
            } else {
                rs = st.executeQuery("select fichedestock.codnum,max(fichedestock.dateenr),fichedestock.qteent,fichedestock.puent,fichedestock.qtesor,fichedestock.pusor,fichedestock.qtedes,fichedestock.qtesto from fichedestock inner join stocker on stocker.codprod=fichedestock.codprod inner join produit on produit.codprod=stocker.codprod where fichedestock.codprod='" + cg.getCodrod(txtCode.getText()) + "' and dateenr='" + madate + "'");
                while (rs.next()) {
                    codnum = rs.getInt(1);
                    dateenr = rs.getString(2);
                    qteent = rs.getDouble(3);
                    puent = rs.getDouble(4);
                    qtesor = rs.getDouble(5);
                    pusor = rs.getDouble(6);
                    qtedes = rs.getDouble(7);
                    qtesto = rs.getDouble(8);
                }
                qtesto = (qtesto - qteent) + Double.parseDouble(txtQte.getText()) - qtedes;
                st.executeUpdate("update fichedestock set codprod='" + cg.getCodrod(txtCode.getText()) + "',dateenr='" + madate + "',qteent='" + txtQte.getText() + "',puent='" + cg.getPaUnitaire(cmbProd.getSelectedItem().toString()) + "',qtesor='" + 0 + "',pusor='" + cg.getPvUnitaire(cmbProd.getSelectedItem().toString()) + "',qtedes='" + 0 + "',qtesto='" + qtesto + "' where codnum='" + codnum + "'");
            }
            rs.close();
            st.close();
        } catch (SQLException e) {
            cg.boiteDeDialogue(e.toString(), "erreur");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Stock dialog = new Stock(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chExp;
    public javax.swing.JComboBox<String> cmbProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtCode;
    private com.toedter.calendar.JDateChooser txtDateExp;
    private com.toedter.calendar.JDateChooser txtDateFab;
    private javax.swing.JTextField txtQte;
    // End of variables declaration//GEN-END:variables
}
